### ISSUE TITLE
NoSuchElementException while updating light causes light to no longer update properly

### ISSUE THREAD

**Issue by flori-schwa** [flori-schwa/VarLightOld#11]
Paper 156

VarLight [Version ce4e551](https://github.com/flori-schwa/VarLight/tree/ce4e551e67080da0a4340aa8d9910a04ffb990cd) (Not confirmed for 1.4.5 yet)

Stacktrace:
```
[17:19:18 WARN]: [VarLight] Plugin VarLight vce4e551 generated an exception while executing task 2933
java.util.NoSuchElementException: null
        at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:470) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.LightEngineGraph.b(SourceFile:190) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.LightEngineStorage.c(SourceFile:353) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.LightEngineBlock.a(SourceFile:129) ~[patched_1.14.4.jar:git-Paper-156]
        at me.shawlaf.varlight.nms.NmsAdapter.lambda$updateBlockLight$0(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-156]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-156]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-156]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by flori-schwa** [comment]
[Should hopefully be fixed in 1.4.6](https://github.com/flori-schwa/VarLight/releases/tag/1.4.6)
