### ISSUE TITLE
Varlight [1.15.1] Error on startup

### ISSUE THREAD

**Issue by ItzSkyy** [flori-schwa/VarLightOld#18]
Using LightAPI (up to date)

`[20:53:42] [Server thread/ERROR]: Error occurred while enabling VarLight v1.7 (Is it up to date?)
java.lang.RuntimeException: Migration Failed: null
    at me.shawlaf.varlight.spigot.persistence.migrate.data.VLDBMigration.test(VLDBMigration.java:81) ~[?:?]
    at me.shawlaf.varlight.spigot.persistence.migrate.data.VLDBMigration.test(VLDBMigration.java:20) ~[?:?]
    at me.shawlaf.varlight.spigot.persistence.migrate.LightDatabaseMigrator.runMigrations(LightDatabaseMigrator.java:69) ~[?:?]
    at me.shawlaf.varlight.spigot.persistence.WorldLightSourceManager.<init>(WorldLightSourceManager.java:48) ~[?:?]
    at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:198) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
    at me.shawlaf.varlight.spigot.VarLightPlugin.onEnable(VarLightPlugin.java:99) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-32]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-32]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-32]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-32]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-32]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-32]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-32]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-32]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
    at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
    at me.shawlaf.varlight.persistence.vldb.VLDBInputStream.readInt16(VLDBInputStream.java:130) ~[?:?]
    at me.shawlaf.varlight.persistence.vldb.VLDBInputStream.readChunk(VLDBInputStream.java:88) ~[?:?]
    at me.shawlaf.varlight.persistence.vldb.VLDBInputStream.readAll(VLDBInputStream.java:71) ~[?:?]
    at me.shawlaf.varlight.spigot.persistence.migrate.data.VLDBMigration.test(VLDBMigration.java:49) ~[?:?]`

**Comment by flori-schwa** [comment]
May I have contents of your varlight/ folder in your world folder to try and reproduce this issue?
Also the entire startup log would be nice to see if it did succeed in migrating some files.

**Comment by ItzSkyy** [comment]
Default code when generated
```
`# VARLIGHT PLUGIN CONFIGURATION
# -------------------------------------------------------------------------------------------
# "autosave" Controls how the plugin automatically saves custom light sources.
# Custom light sources are saved in <world-folder>/varlight/
# A value greater than zero will automatically save all custom light sources every N minutes.
# Setting this value to 0 will disable automatic saving of custom light sources completely
# and all custom light sources must be saved manually using the built-in command
# A value less than zero will automatically save all custom light sources of a world as
# soon as that world gets saved.
# -------------------------------------------------------------------------------------------
# "autosave-logpersist" Controls if information about the autosave should be printed
# to the server console log
# -------------------------------------------------------------------------------------------
# "requiredPermission" controls the Permission node required to use the plugins functionality
# -------------------------------------------------------------------------------------------
# "whitelist" Controls in which worlds the plugin will function
# -------------------------------------------------------------------------------------------
# "blacklist" Controls in which worlds the plugin will not function
# -------------------------------------------------------------------------------------------


item: "GLOWSTONE_DUST"
autosave: 5
autosave-logpersist: 'true'
requiredPermission: ''
whitelist: []
blacklist: []`
```

**Comment by flori-schwa** [comment]
I meant the files in world/varlight not plugins/varlight

**Comment by ItzSkyy** [comment]
Oh yea...




[VarLight.zip](https://github.com/flori-schwa/VarLight/files/4013706/VarLight.zip)

I can Send log in an hour when I have better access

**Comment by ItzSkyy** [comment]
Here is log, apologies for delay (starts at line 392)

[Log.txt](https://github.com/flori-schwa/VarLight/files/4013907/Log.txt)

**Comment by flori-schwa** [comment]
The issue seems to be in the Java implementation of VLDB because [The CLI tool I wrote in C#](https://github.com/flori-schwa/VLDBExplorer) can easily print out all light sources in the affected file

**Comment by flori-schwa** [comment]
[Fixed in latest release](https://github.com/flori-schwa/VarLight/releases/tag/1.7.1)
