### ISSUE TITLE
BlockExplodeEvent error

### ISSUE THREAD

**Issue by SlimeDog** [flori-schwa/VarLightOld#22]
Spigot 1.15.1
VarLight 1.8.1

Server has only one varlight instance. There were no players in that world.

config.yml
```
check-update: true
item: minecraft:glowstone_dust
autosave: -5
requiredPermission: varlight.use
whitelist:
- world
blacklist: []
vldb-deflated: true
stepsize-gamemode: SURVIVAL
varlight-reclaim: true
log-debug: false
```
Error:
```
[09:55:53] [Server thread/ERROR]: Could not pass event BlockExplodeEvent to VarLight v1.8.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.Explosion.a(Explosion.java:253) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:854) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.WorldServer.createExplosion(WorldServer.java:1284) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:843) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.createExplosion(CraftWorld.java:840) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.createExplosion(CraftWorld.java:835) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at com.extrahardmode.task.CreateExplosionTask.createExplosion(CreateExplosionTask.java:189) ~[?:?]
        at com.extrahardmode.task.CreateExplosionTask.run(CreateExplosionTask.java:88) ~[?:?]
        at com.extrahardmode.features.monsters.Blazes.onEntityDeath(Blazes.java:167) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor324.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1326) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1275) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1122) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityBlaze.mobTick(SourceFile:116) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:661) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2519) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:504) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityMonster.movementTick(SourceFile:39) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityBlaze.movementTick(SourceFile:110) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2351) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:623) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.World.a(World.java:718) [spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395) [spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076) [spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.onBlockExplode(VarLightPlugin.java:487) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1.jar-2020-01-15-0736:git-Spigot-037559e-752cf95]
        ... 40 more
```

**Comment by flori-schwa** [comment]
Fixed in [1.8.2](https://github.com/flori-schwa/VarLight/releases/tag/1.8.2)
