### ISSUE TITLE
Can't make light sources

### ISSUE THREAD

**Issue by Sotlol1** [flori-schwa/VarLightOld#27]
I'm on 1.15.2 and have LightAPI.

Error log
`> [08:31:41] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to VarLight v1.8.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:541) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:528) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [server.jar:git-Spigot-8faa8b4-fba9f48]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-8faa8b4-fba9f48]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: me.shawlaf.varlight.spigot.nms.LightUpdateFailedException: LightAPI not enabled or deleteLight Event cancelled!
at me.shawlaf.varlight.spigot.nms.NmsAdapter.updateBlockLight(NmsAdapter.java:169) ~[VarLight-1.8.3-MC-1.15.x.jar:?]
at me.shawlaf.varlight.spigot.util.LightSourceUtil.placeNewLightSource(LightSourceUtil.java:64) ~[VarLight-1.8.3-MC-1.15.x.jar:?]
at me.shawlaf.varlight.spigot.VarLightPlugin.onInteract(VarLightPlugin.java:325) ~[VarLight-1.8.3-MC-1.15.x.jar:?]
at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-8faa8b4-fba9f48]`

**Comment by flori-schwa** [comment]
LightAPI is either disabled or another plug-in canceled LightAPI's light update event. This won't be an issue in the next release as the LightAPI dependency will be removed. See the "dev" branch

**Comment by Sotlol1** [comment]
Okey will hold off until then :) Tried it on a clean test server and it didn't work there either so yeah. Thank you
