### ISSUE TITLE
Java 12+ (Reflection)

### ISSUE THREAD

**Issue by Pet0203** [flori-schwa/VarLightOld#33]
Hello there!
I am working on getting a server to work with Java 14, but the reflection framework got restricted in Java 12, could you check if there are any quick fixes to this issue?

`[21:56:30] [Server thread/INFO]: [VarLight] Enabling VarLight v1.9
[21:56:30] [Server thread/INFO]: [VarLight] Enabling in World [world]
[21:56:30] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[21:56:30] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.util.ReflectionHelper$FieldAccess.lambda$static$2(ReflectionHelper.java:124)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.util.ReflectionHelper$FieldAccess.apply(ReflectionHelper.java:142)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.util.ReflectionHelper.fieldAccess(ReflectionHelper.java:36)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.util.ReflectionHelper.access$300(ReflectionHelper.java:8)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.util.ReflectionHelper$Safe.setValue(ReflectionHelper.java:186)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.util.ReflectionHelper$Safe.set(ReflectionHelper.java:203)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.nms.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:69)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:162)
[21:56:30] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
[21:56:30] [Server thread/WARN]: 	at me.shawlaf.varlight.spigot.VarLightPlugin.onEnable(VarLightPlugin.java:119)
[21:56:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:56:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:56:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[21:56:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[21:56:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[21:56:30] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:487)
[21:56:30] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[21:56:30] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:891)
[21:56:30] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)`

**Comment by flori-schwa** [comment]
Sadly, reflection is required to modify the Light Engine (https://github.com/flori-schwa/VarLight/blob/1.10.1/v1_15_R1/src/me/shawlaf/varlight/spigot/nms/NmsAdapter.java#L53), I can look into using LightAPI again. Not sure if LightAPI needs Reflection though.

**Comment by Pet0203** [comment]
Thank you for the fast response. LightAPI uses reflection too. I think I'll have to settle for Java 11. But you never know when Mojang decides to jump versions. Reflection is "abused" in many places, that's why they removed it.
