### ISSUE TITLE
Loadup fail for non-overworld worlds

### ISSUE THREAD

**Issue by ghost** [flori-schwa/VarLightOld#4]
Not sure exactly what you need, but on startup:
`[00:20:26] [Server thread/INFO]: [VarLight] Enabling VarLight v1.3
[00:20:26] [Server thread/INFO]: [VarLight] Created a new Lightsource Persistor for world "world"
[00:20:26] [Server thread/INFO]: [VarLight] Created a new Lightsource Persistor for world "world_nether"
[00:20:26] [Server thread/INFO]: [VarLight] Created a new Lightsource Persistor for world "world_the_end"
[00:20:26] [Server thread/INFO]: [VarLight] Injected custom IBlockAccess into world "world"
[00:20:26] [Server thread/ERROR]: Error occurred while enabling VarLight v1.3 (Is it up to date?)
java.lang.ClassCastException: net.minecraft.server.v1_14_R1.LightEngineLayerEventListener$Void cannot be cast to net.minecraft.server.v1_14_R1.LightEngineLayer
	at me.florian.varlight.nms.NmsAdapter_1_14_R1.injectToEngine(NmsAdapter_1_14_R1.java:230) ~[?:?]
	at me.florian.varlight.nms.NmsAdapter_1_14_R1.injectCustomIBlockAccess(NmsAdapter_1_14_R1.java:221) ~[?:?]
	at me.florian.varlight.nms.NmsAdapter_1_14_R1.onEnable(NmsAdapter_1_14_R1.java:99) ~[?:?]
	at me.florian.varlight.VarLightPlugin.onEnable(VarLightPlugin.java:109) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

Then when I try to right click:
`[00:24:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to VarLight v1.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:423) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:435) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1263) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot.jar:git-Spigot-1eece4f-8879c31]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.UnsupportedOperationException: Not used for v1_14_R1!
	at me.florian.varlight.nms.NmsAdapter_1_14_R1.recalculateBlockLight(NmsAdapter_1_14_R1.java:315) ~[?:?]
	at me.florian.varlight.LightUpdaterBuiltIn.setLight(LightUpdaterBuiltIn.java:34) ~[?:?]
	at me.florian.varlight.VarLightPlugin.onInteract(VarLightPlugin.java:239) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-1eece4f-8879c31]
	... 19 more
`
If you need any more info, I'll try to provide it

**Comment by flori-schwa** [comment]
My test server only has the overworld loaded, that might be the issue

**Comment by flori-schwa** [comment]
The issue is right here: https://github.com/flori-schwa/VarLight/blob/master/v1_14_R1/src/me/florian/varlight/nms/NmsAdapter_1_14_R1.java#L221
Don't know what made me think I need to edit the skylight engine. Will fix ASAP

**Comment by flori-schwa** [comment]
You can download the new version here: https://github.com/flori-schwa/VarLight/releases/tag/1.3.2
