### ISSUE TITLE
[BUG] Plugin error on startup (Yatopia)

### ISSUE THREAD

**Issue by WolverStones** [flori-schwa/VarLightOld#41]
I tried to run the plugin at https://github.com/YatopiaMC/Yatopia but it doesn't load and doesn't work, so I guess it's not supported, but I want to ask if it would add support ..?

Full log: https://pastebin.com/W2tDj1kD

 Yatopia version git-Yatopia-"89064f4" (MC: 1.16.4)

`[VarLight] Enabling in World [world]
[13:41:01 ERROR]: Could not pass event WorldLoadEvent to VarLight v1.12.8
java.lang.ClassCastException: class net.minecraft.server.v1_16_R3.LightEngineThreaded$1 cannot be cast to class net.minecraft.server.v1_16_R3.LightEngineBlock (net.minecraft.server.v1_16_R3.LightEngineThreaded$1 and net.minecraft.server.v1_16_R3.LightEngineBlock are in unnamed module of loader 'app')
        at me.shawlaf.varlight.spigot.nms.v1_16_R3.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:61) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:186) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.worldLoad(VarLightPlugin.java:275) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:453) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[13:41:01 INFO]: Preparing start region for dimension minecraft:the_nether
[13:41:01 INFO]: Loaded 0 spawn chunks for world world_nether
[13:41:01 INFO]: Time elapsed: 76 ms
[13:41:01 INFO]: [VarLight] Enabling in World [world_nether]
[13:41:01 ERROR]: Could not pass event WorldLoadEvent to VarLight v1.12.8
java.lang.ClassCastException: class net.minecraft.server.v1_16_R3.LightEngineThreaded$1 cannot be cast to class net.minecraft.server.v1_16_R3.LightEngineBlock (net.minecraft.server.v1_16_R3.LightEngineThreaded$1 and net.minecraft.server.v1_16_R3.LightEngineBlock are in unnamed module of loader 'app')
        at me.shawlaf.varlight.spigot.nms.v1_16_R3.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:61) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:186) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.worldLoad(VarLightPlugin.java:275) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:453) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[13:41:01 INFO]: Preparing start region for dimension minecraft:the_end
[13:41:01 INFO]: Loaded 0 spawn chunks for world world_the_end
[13:41:01 INFO]: Time elapsed: 242 ms
[13:41:01 INFO]: [VarLight] Enabling in World [world_the_end]
[13:41:01 ERROR]: Could not pass event WorldLoadEvent to VarLight v1.12.8
java.lang.ClassCastException: class net.minecraft.server.v1_16_R3.LightEngineThreaded$1 cannot be cast to class net.minecraft.server.v1_16_R3.LightEngineBlock (net.minecraft.server.v1_16_R3.LightEngineThreaded$1 and net.minecraft.server.v1_16_R3.LightEngineBlock are in unnamed module of loader 'app')
        at me.shawlaf.varlight.spigot.nms.v1_16_R3.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:61) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:186) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.worldLoad(VarLightPlugin.java:275) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:453) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"89064f4"]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by bobhenl** [comment]
Similar errors
```
[15:39:55] [Server thread/ERROR]: Could not pass event WorldLoadEvent to VarLight v1.12.8
java.lang.ClassCastException: class com.tuinity.tuinity.chunk.light.StarLightInterface$2 cannot be cast to class net.minecraft.server.v1_16_R3.LightEngineBlock (com.tuinity.tuinity.chunk.light.StarLightInterface$2 and net.minecraft.server.v1_16_R3.LightEngineBlock are in unnamed module of loader 'app')
	at me.shawlaf.varlight.spigot.nms.v1_16_R3.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:61) ~[?:?]
	at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:186) ~[?:?]
	at me.shawlaf.varlight.spigot.VarLightPlugin.worldLoad(VarLightPlugin.java:275) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-7]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:449) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-7]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
```
[15:40:06] [Server thread/INFO]: [VarLight] Enabling in World [world_nether]
[15:40:06] [Server thread/ERROR]: Could not pass event WorldLoadEvent to VarLight v1.12.8
java.lang.ClassCastException: class com.tuinity.tuinity.chunk.light.StarLightInterface$2 cannot be cast to class net.minecraft.server.v1_16_R3.LightEngineBlock (com.tuinity.tuinity.chunk.light.StarLightInterface$2 and net.minecraft.server.v1_16_R3.LightEngineBlock are in unnamed module of loader 'app')
	at me.shawlaf.varlight.spigot.nms.v1_16_R3.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:61) ~[?:?]
	at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:186) ~[?:?]
	at me.shawlaf.varlight.spigot.VarLightPlugin.worldLoad(VarLightPlugin.java:275) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-7]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:1180) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:590) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:322) ~[patched_1.16.5.jar:git-Yatopia-7]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:499) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:480) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:455) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:767) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:307) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-7]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
@flori-schwa

**Comment by mikroskeem** [comment]
This is because Tuinity's Starlight is not supported.
