### ISSUE TITLE
Purpur compatibility

### ISSUE THREAD

**Issue by SlimeDog** [flori-schwa/VarLightOld#47]
**Is your feature request related to a problem? Please describe.**
With nothing else to do this weekend, I decided to experiment with Purpur. VarLight is unhappy, no doubt due to the StarLight reimplementation of lighting. (So probably incompatible with Tuinity also.)

**Describe the solution you'd like**
Whatever is required.

**Describe alternatives you've considered (optional)**
Initial inquiry.

**Additional context**
```
[15:42:20] [Server thread/INFO]: [VarLight] Enabling in World [world]
[15:42:20] [Server thread/ERROR]: Could not pass event WorldLoadEvent to VarLight v1.12.8
java.lang.ClassCastException: class com.tuinity.tuinity.chunk.light.StarLightInterface$2 cannot be cast to class net.minecraft.server.v1_16_R3.LightEngineBlock (com.tuinity.tuinity.chunk.light.StarLightInterface$2 and net.minecraft.server.v1_16_R3.LightEngineBlock are in unnamed module of loader 'app')
        at me.shawlaf.varlight.spigot.nms.v1_16_R3.NmsAdapter.enableVarLightInWorld(NmsAdapter.java:61) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.enableInWorld(VarLightPlugin.java:186) ~[?:?]
        at me.shawlaf.varlight.spigot.VarLightPlugin.worldLoad(VarLightPlugin.java:275) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor147.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-978]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-978]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-978]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-978]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:450) ~[patched_1.16.5.jar:git-Purpur-978]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[patched_1.16.5.jar:git-Purpur-978]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:942) ~[patched_1.16.5.jar:git-Purpur-978]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-978]
```

**Comment by flori-schwa** [comment]
Might include it in the rewrite. which I am planning on continuing soon

**Comment by SlimeDog** [comment]
No worries. I don't use Purpur normally, and it looks like not that many servers do, compared with Spigot or Paper. It was just a test, on a long weekend with nothing much to do.

**Comment by LaurenceBarnes** [comment]
Tuinity is used by many larger servers though ^^

**Comment by whalehub** [comment]
@flori-schwa Any update on this?

**Comment by NickAcPT** [comment]
Many servers do indeed use Tuinity(which is the Paper fork that added Starlight) or forks of it.
So please add support for it on the rewrite.

**Comment by Tanerx** [comment]
Same error. Please add StarLight suppport for 1.16.5 and +.
