### ISSUE TITLE
ArrayIndexOutOfBoundsException saving chunk

### ISSUE THREAD

**Issue by SlimeDog** [flori-schwa/VarLightOld#9]
Spigot 1.14.4 (Jenkins 2468) git-Spigot-065a373-03b145b (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
LightAPI 3.3.2
VarLight 1.4.5-LightAPI-1.14

This error occurs occasionally, and randomly. There are no players on this test server. The stack trace does not identify any plugins, but it appears to be related to lighting. I do not recall seeing this error prior to VarLIght. So I'm wondering if the stack points to something useful. Any help appreciated.
```
[17:35:38] [Server thread/ERROR]: Failed to save chunk 1,-1
java.lang.ArrayIndexOutOfBoundsException: Index 49 out of bounds for length 33
        at org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:215) ~[spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:269) ~[spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:699) ~[spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$16(PlayerChunkMap.java:396) ~[spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:378) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:344) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:337) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:259) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar-2019-09-09-0727:git-Spigot-065a373-03b145b]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by flori-schwa** [comment]
Does this still occur?

**Comment by SlimeDog** [comment]
Yes, it does. Frequently.

Spigot 1.14.4 (Jenkins 2482)
LightAPI 3.4.1
VarLight 1.4.5-LightAPI-1.14

**Comment by flori-schwa** [comment]
Does this also occur when you are not using LightAPI?

**Comment by SlimeDog** [comment]
Yes. It occurs on my test servers when no one is connected. I have not observed that it happens (or not) when players are connected.

**Comment by SlimeDog** [comment]
I'm sorry, did you mean with LightAPI disabled but VarLight enabled?

**Comment by flori-schwa** [comment]
Yeah, does it still occur when you are using anything but the `VarLight-(plugin_version)-LightAPI-1.14.jar`  version?

**Comment by SlimeDog** [comment]
That is the only version of VarLight I have tested. Do you want me to disable VarLight, to determine if the error recurs? Or do you want me to test a non-LightAPI version of VarLight?

**Comment by flori-schwa** [comment]
both would be best. To check whether this is caused by VarLight, LightApi or perhaps another plugin on your server.

**Comment by SlimeDog** [comment]
OK. The issue is non-deterministic, but has occurred 11 times in the last 3 days. For the test 1, I have disabled
- VarLight
- LightAPI
- ShinyItems (which also depends on LightAPI)

I will run the server for a few days, to determine if the issue recurs in that state.

**Comment by flori-schwa** [comment]
this is running on a test server with the same setup as your main, correct?

**Comment by SlimeDog** [comment]
I run two test servers. They are clones, except for the three disabled plugins on the one now running test 1. The errors have occurred on both.

**Comment by SlimeDog** [comment]
Test 1 has produced the error. So it is not caused by one of the LightAPI-related plugins. Now I'll start winnowing based on my minimal subset of plugins.

Thanks for thinking about the question.
